# Generated by Django 2.2.4 on 2021-02-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_url',
            field=models.URLField(default=''),
        ),
    ]
