# Generated by Django 2.2.4 on 2021-02-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0002_player_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='display_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
