# Generated by Django 2.2.4 on 2021-03-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0003_auto_20210221_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
    ]
