# Generated by Django 3.0.2 on 2020-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0019_auto_20200810_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='audio',
            field=models.FileField(null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='level',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
