# Generated by Django 3.0.2 on 2020-08-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure', '0021_auto_20200811_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='display_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='display_video',
            field=models.BooleanField(default=False),
        ),
    ]
